GAP.InsurancePolicy/GAP.InsurancePolicy.Web/Controllers/InsuranceController.cs
using GAP.InsurancePolicy.BusinessLogic.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GAP.InsurancePolicy.Web.Controllers
{
    [Authorize]
    public class InsuranceController : Controller
    {

        private IInsuranceBL _insuranceBL;

        public InsuranceController(IInsuranceBL insuranceBL)
        {
            this._insuranceBL = insuranceBL;
        }
        //
        // GET: /Insurance/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetInsuranceList()
        {
            var list = _insuranceBL.getList();
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetCoverageByInsuranceList(int insurancePolicyId)
        {
            var list = _insuranceBL.getList();
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Save(GAP.InsurancePolicy.Entities.InsurancePolicy record)
        {
            var result = _insuranceBL.Save(record);
            return Json(new { result = true });
        }        

    }
}

GAP.InsurancePolicy/GAP.InsurancePolicy.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - GAP Seguros</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css" />

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("GAP Seguros", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    
                    <li>@Html.ActionLink("Seguros", "Index", "Insurance")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - GAP Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>